const PulsesApi = [
    {   
        id: '3001',
        title: 'Black Chickpeas',
        rating: 4.5,
        price: 100,
        maxPrice: 110,
        quantity: '1kg',
        url: require('../../../src/assets/images/Pulses/Black_Chickpeas/BlackChickpeas1.webp'),
        numberOfItem: '1',
    },
    {   
        id: '3002',
        title: 'Black lentils',
        rating: 4.5,
        price: 100,
        maxPrice: 110,
        quantity: '1kg',
        url: require('../../../src/assets/images/Pulses/Black_Lentils/BlackLentils1.jpg'),
        numberOfItem: '1',
    },
    {   
        id: '3003',
        title: 'Chickpeas',
        rating: 4.5,
        price: 80,
        maxPrice: 100,
        quantity: '1kg',
        url: require('../../../src/assets/images/Pulses/Chickpeas/Chickpeas1.jpg'),
        numberOfItem: '1',
    },
    {   
        id: '3004',
        title: 'Kidney Beans',
        rating: 4.5,
        price: 120,
        maxPrice: 140,
        quantity: '1kg',
        url: require('../../../src/assets/images/Pulses/Kidney_Beans/KidneyBeans1.webp'),
        numberOfItem: '1',
    },
    {   
        id: '3005',
        title: 'Moong Dal',
        rating: 4.5,
        price: 100,
        maxPrice: 110,
        quantity: '1kg',
        url: require('../../../src/assets/images/Pulses/Moong_Dal/MoongDal1.jpg'),
        numberOfItem: '1',
    },
    {   
        id: '3006',
        title: 'Toor Dal',
        rating: 4.5,
        price: 90,
        maxPrice: 110,
        quantity: '1kg',
        url: require('../../../src/assets/images/Pulses/Pigeon_Peas_(ToorDal)/ToorDall1.webp'),
        numberOfItem: '1',
    },
    {   
        id: '3007',
        title: 'Red Lentils',
        rating: 4.5,
        price: 100,
        maxPrice: 110,
        quantity: '1kg',
        url: require('../../../src/assets/images/Pulses/Red_Lentils/RedLentils1.webp'),
        numberOfItem: '1',
    },
    {   
        id: '3008',
        title: 'Chana Dal',
        rating: 4.5,
        price: 80,
        maxPrice: 100,
        quantity: '1kg',
        url: require('../../../src/assets/images/Pulses/Chana_Dal/ChanaDal1.jpg'),
        numberOfItem: '1',
    },
    {   
        id: '3009',
        title: 'Whole Moong Beans',
        rating: 4.5,
        price: 100,
        maxPrice: 120,
        quantity: '1kg',
        url: require('../../../src/assets/images/Pulses/Whole_Moong_Beans/MoongBeans2.jpg'),
        numberOfItem: '1',
    },
]

export default PulsesApi;