const images = {
  banana: require('../assests/banana.webp'),
  Tomato: require('../assests/Tomato.webp'),
  shopKeeper6: require('../assests/shopkeeper6.webp'),
  shopKeeper4: require('../assests/shopkeeper4.webp'),
  grapes: require('../assests/grapes.png'),
  grocery1: require('../assests/grocery1.png'),
  googleLogo: require('../assests/google-logo.png'),
  facebook: require('../assests/facebook.png'),
  Broccoli: require('../assests/Broccoli.jpeg'),
  cabbage: require('../assests/cabbage.jpeg'),
  Lettuce: require('../assests/Lettuce.jpeg'),
  mango: require('../assests/mango.jpeg'),
  pineapple: require('../assests/pineapple.jpeg'),
  radish: require('../assests/radish.jpeg'),
  shopKeeper1: require('../assests/shopkeeper1.jpeg'),
  shopKeeper2: require('../assests/shopkeeper2.jpeg'),
  shopKeeper3: require('../assests/Shopkeeper3.jpeg'),
  shopKeeper5: require('../assests/shopkeeper5.jpeg'),
  shopKeeper7: require('../assests/shopkeeper7.jpeg'),
  shopKeeper8: require('../assests/shopkeeper8.jpeg'),
  shopKeeper9: require('../assests/shopkeeper9.jpeg'),
  shopKeeper10: require('../assests/shopkeeper10.jpeg'),
  vegseller: require('../assests/veg seller.jpeg'),
};
export default images;
