import React from 'react';

const Data = [
  {
    id: '1',
    title:'Fennel',
    price: '$0.27 each',
    image: require('../assets/fresh-fennel.webp'),
    quantity:2,
    oldPrice: 240,
  },
  {
    id: '2',
    title:'Radishes',
    price: '$0.27 each',
    image: require('../assets/reddishimage.jpeg'),
    quantity:3,
    oldPrice: 20,
  },
  {
    id: '3',
    title:'Banana',
    price: '$0.27 each',
    image: require('../assets/banana.jpeg'),
    quantity:4,
    oldPrice: 10,
  },
  {
    id: '4',
    title:'Carrots',
    price: '$0.27 each',
    image: require('../assets/carrots.jpeg'),
    quantity:5,
    oldPrice: 20,
  },
  {
    id: '5',
    title:'Beetroot',
    price: '$0.27 each',
    image: require('../assets/beetroot.jpeg'),
    quantity:6,
    oldPrice: 30,
  },
  {
    id: '6',
    title:'Garlic',
    price: '$0.27 each',
    image: require('../assets/garlic.jpeg'),
    quantity:7,
    oldPrice: 20,
  },
  {
    id: '7',
    title:'Ladyfinger',
    price: '$0.27 each',
    image: require('../assets/ladyfinger.jpeg'),
    quantity:8,
    oldPrice: 2,
  },
  {
    id: '8',
    title:'Brinjal',
    price: '$0.27 each',
    image: require('../assets/brinjal.jpeg'),
    quantity:9,
    oldPrice: 70,
  },
  {
    id: '9',
    title:'Brocolli',
    price: '$0.27 each',
    image: require('../assets/brocolli.jpeg'),
    quantity:10,
    oldPrice: 10,
  },
  {
    id: '10',
    title:'Mushroom',
    price: '$0.27 each',
    image: require('../assets/mushroom.jpeg'),
    quantity:11,
    oldPrice: 50,
  },
];

export default Data;
