import React from 'react';

const Data = [
  {
    id: '1',
    title:'Fennel',
    dollar: '$0.27 each',
    image: require('../assets/fresh-fennel.webp'),
    quantity:2,
    numberOfItem: 2,
  },
  {
    id: '2',
    title:'Radishes',
    dollar: '$0.27 each',
    image: require('../assets/reddishimage.jpeg'),
    quantity:3,
    numberOfItem: 1,
  },
  {
    id: '3',
    title:'Banana',
    dollar: '$0.27 each',
    image: require('../assets/banana.jpeg'),
    quantity:4,
    numberOfItem: 4,
  },
  {
    id: '4',
    title:'Carrots',
    dollar: '$0.27 each',
    image: require('../assets/carrots.jpeg'),
    quantity:5,
    numberOfItem: 2,
  },
  {
    id: '5',
    title:'Beetroot',
    dollar: '$0.27 each',
    image: require('../assets/beetroot.jpeg'),
    quantity:6,
    numberOfItem: 3,
  },
  {
    id: '6',
    title:'Garlic',
    dollar: '$0.27 each',
    image: require('../assets/garlic.jpeg'),
    quantity:7,
    numberOfItem: 1,
  },
  {
    id: '7',
    title:'Ladyfinger',
    dollar: '$0.27 each',
    image: require('../assets/ladyfinger.jpeg'),
    quantity:8,
    numberOfItem: 2,
  },
  {
    id: '8',
    title:'Brinjal',
    dollar: '$0.27 each',
    image: require('../assets/brinjal.jpeg'),
    quantity:9,
    numberOfItem: 1,
  },
  {
    id: '9',
    title:'Brocolli',
    dollar: '$0.27 each',
    image: require('../assets/brocolli.jpeg'),
    quantity:10,
    numberOfItem: 1,
  },
  {
    id: '10',
    title:'Mushroom',
    dollar: '$0.27 each',
    image: require('../assets/mushroom.jpeg'),
    quantity:11,
    numberOfItem: 1,
  },
];

export default Data;
