export const ActionTypes = {
  USERDATA: 'USERDATA',
  REGDATA: 'REGDATA',
  ADDCART: 'ADDCART',
  INCREMENT_ITEM: 'INCREMENT_ITEM',
  DECREMENT_ITEM: 'DECREMENT_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  PRODUCT_DATA: 'PRODUCT_DATA',
  Add_Address: ' Add_Address',
  REMOVE_ADDRESS: 'REMOVE_ADDRESS',
  EDIT_ADDRESS: 'EDIT_ADDRESS',
};
