export const ActionType = {
    LOGIN_USER: 'LOGIN_USER',
    REGISTER_USER:"REGISTER_USER",
    SET_FETCHING:"SET_FETCHING",
    SET_INIT_DATA:"SET_INIT_DATA",
    ADD_ITEM:"ADD_ITEM",
    REMOVE_ITEM:"REMOVE_ITEM"
  };
  