export const ActionType = {
  USER_DETAILS: 'USER_DETAILS',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_CART: 'REMOVE_CART',
  INCREASE_CART_ITEM: 'INCREASE_CART_ITEM',
  DECREASE_CART_ITEM: 'DECREASE_CART_ITEM',
  USER_ID: 'USER_ID',
  SET_FETCHING:"SET_FETCHING",
  SET_INIT_DATA:"SET_INIT_DATA",
};
