export const ActionTypes = {
  USER_ID: 'USER_ID',
  REGISTER_DETAILS: 'REGISTER_DETAILS',

  ADD_FRUITS_TO_CART: 'ADD_FRUITS_TO_CART',
  ITEMS_INCRIMENT: 'ITEMS_INCRIMENT',
  ITEMS_DECREMENT: 'ITEMS_DECREMENT',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',

  MANAGE_ADDRESSES: 'MANAGE_ADDRESSES',
  DELETE_ADDRESS: 'DELETE_ADDRESS',
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',

  DATA_CALLING: 'DATA_CALLING',
};
