export const ActionTypes = {
  USER_ID: 'USER_ID',
  REGISTER_DETAILS: 'REGISTER_DETAILS',

  ADD_FRUITS_TO_CART: 'ADD_FRUITS_TO_CART',
  ITEMS_INCRIMENT: 'ITEMS_INCRIMENT',
  ITEMS_DECREMENT: 'ITEMS_DECREMENT',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',

  MANAGE_ADDRESSES: 'MANAGE_ADDRESSES',
  DELETE_ADDRESS: 'DELETE_ADDRESS',
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',

  DATA_CALLING: 'DATA_CALLING',

  COMPONENT_CHANGE_BY_INDEX: 'COMPONENT_CHANGE_BY_INDEX',

  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  REMOVE_TO_WISHLIST: 'REMOVE_TO_WISHLIST',

  // Cart checkoutDetails
  ORDERED_PRODUCTS: 'ORDERED_PRODUCTS',
  ORDERED_PRODUCTS_PRICE_DETAILS: 'ORDERED_PRODUCTS_PRICE_DETAILS',
  SELECTED_ADDRESS: 'SELECTED_ADDRESS',
  DELIVERY_DATE: 'DELIVERY_DATE',
  DELIVERY_TIME: 'DELIVERY_TIME',
  PAYMENT_METHOD: 'PAYMENT_METHOD',
  CHECKOUT_DETAILS: 'CHECKOUT_DETAILS',
};
