// USER ACTIONS
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT';

export const ADD_ADDRESS = 'ADD_ADDRESS';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
