export const USER_DATA = 'USER_DATA';
export const ADD_CART_PRODUCTS = 'ADD_CART_PRODUCTS';
export const REMOVE_CART_PRODUCTS = ' REMOVE_CART_PRODUCTS';
export const INCREASE_CART = 'INCREASE_CART';
export const DECREASE_CART = 'DECREASE_CART';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
